/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penerimaan.desa;

/**
 *
 * @author Imul
 */
public class History extends javax.swing.JFrame {

    private int role;

    /**
     * Creates new form History
     */
    public History() {
        initComponents();
    }
    
    public History(int role){
        initComponents();
        this.role = role;
        if (role > 0) {
            jPanel10.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Psamping1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lblHome1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblFuzzy1 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lblEvaluasi1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lblHistory1 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        lblStruktur2 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        lblProfilDesa1 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        lblStruktur3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        Psamping1.setBackground(new java.awt.Color(0, 204, 204));
        Psamping1.setPreferredSize(new java.awt.Dimension(160, 650));
        Psamping1.setLayout(new javax.swing.BoxLayout(Psamping1, javax.swing.BoxLayout.Y_AXIS));

        jPanel11.setBackground(new java.awt.Color(0, 204, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel11.setLayout(new java.awt.GridLayout(1, 1));

        lblHome1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHome1.setForeground(new java.awt.Color(255, 255, 255));
        lblHome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome1.setText("Home");
        lblHome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHome1MouseClicked(evt);
            }
        });
        jPanel11.add(lblHome1);

        Psamping1.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(0, 204, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel12.setPreferredSize(new java.awt.Dimension(72, 31));
        jPanel12.setLayout(new java.awt.GridLayout(1, 1));

        lblFuzzy1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFuzzy1.setForeground(new java.awt.Color(52, 17, 9));
        lblFuzzy1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFuzzy1.setText("Fuzzy");
        lblFuzzy1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFuzzy1MouseClicked(evt);
            }
        });
        jPanel12.add(lblFuzzy1);

        Psamping1.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(0, 204, 204));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel13.setPreferredSize(new java.awt.Dimension(72, 31));
        jPanel13.setLayout(new java.awt.GridLayout(1, 1));

        lblEvaluasi1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblEvaluasi1.setForeground(new java.awt.Color(52, 17, 9));
        lblEvaluasi1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEvaluasi1.setText("Evaluasi");
        lblEvaluasi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEvaluasi1MouseClicked(evt);
            }
        });
        jPanel13.add(lblEvaluasi1);

        Psamping1.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(0, 204, 204));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel14.setPreferredSize(new java.awt.Dimension(72, 31));
        jPanel14.setLayout(new java.awt.GridLayout(1, 1));

        lblHistory1.setBackground(new java.awt.Color(0, 204, 204));
        lblHistory1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHistory1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHistory1.setText("History");
        jPanel14.add(lblHistory1);

        Psamping1.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(0, 204, 204));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel15.setPreferredSize(new java.awt.Dimension(72, 31));
        jPanel15.setLayout(new java.awt.GridLayout(1, 1));

        lblStruktur2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblStruktur2.setForeground(new java.awt.Color(52, 17, 9));
        lblStruktur2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStruktur2.setText("Struktur Desa");
        lblStruktur2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStruktur2MouseClicked(evt);
            }
        });
        jPanel15.add(lblStruktur2);

        Psamping1.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(0, 204, 204));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel16.setPreferredSize(new java.awt.Dimension(72, 31));
        jPanel16.setLayout(new java.awt.GridLayout(1, 1));

        lblProfilDesa1.setBackground(new java.awt.Color(0, 204, 204));
        lblProfilDesa1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblProfilDesa1.setForeground(new java.awt.Color(52, 17, 9));
        lblProfilDesa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfilDesa1.setText("Profil Desa");
        lblProfilDesa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProfilDesa1MouseClicked(evt);
            }
        });
        jPanel16.add(lblProfilDesa1);

        Psamping1.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(0, 204, 204));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel17.setPreferredSize(new java.awt.Dimension(72, 31));
        jPanel17.setLayout(new java.awt.GridLayout(1, 1));

        lblStruktur3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblStruktur3.setForeground(new java.awt.Color(52, 17, 9));
        lblStruktur3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStruktur3.setText("User");
        lblStruktur3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStruktur3MouseClicked(evt);
            }
        });
        jPanel17.add(lblStruktur3);

        Psamping1.add(jPanel17);

        jPanel1.add(Psamping1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        // TODO add your handling code here:
        //        this.setVisible(false);
        //        new FormSuplier().setVisible(true);
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblFuzzyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuzzyMouseClicked
        // TODO add your handling code here:
        //        this.setVisible(false);
        //        new FormBarang().setVisible(true);
    }//GEN-LAST:event_lblFuzzyMouseClicked

    private void lblEvaluasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEvaluasiMouseClicked
        // TODO add your handling code here:
        //        this.setVisible(false);
        //        new FormJadwal().setVisible(true);
    }//GEN-LAST:event_lblEvaluasiMouseClicked

    private void lblStrukturMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStrukturMouseClicked
        // TODO add your handling code here:
        //        this.setVisible(false);
        //        new FormLaporan().setVisible(true);
    }//GEN-LAST:event_lblStrukturMouseClicked

    private void lblProfilDesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProfilDesaMouseClicked
        // TODO add your handling code here:
        //        this.setVisible(false);
        //        new FormAnggota().setVisible(true);
    }//GEN-LAST:event_lblProfilDesaMouseClicked

    private void lblStruktur1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStruktur1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblStruktur1MouseClicked

    private void lblHome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHome1MouseClicked
        // TODO add your handling code here:
        //        this.setVisible(false);
        //        new FormSuplier().setVisible(true);
    }//GEN-LAST:event_lblHome1MouseClicked

    private void lblFuzzy1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFuzzy1MouseClicked
        // TODO add your handling code here:
        //        this.setVisible(false);
        //        new FormBarang().setVisible(true);
    }//GEN-LAST:event_lblFuzzy1MouseClicked

    private void lblEvaluasi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEvaluasi1MouseClicked
        // TODO add your handling code here:
        //        this.setVisible(false);
        //        new FormJadwal().setVisible(true);
    }//GEN-LAST:event_lblEvaluasi1MouseClicked

    private void lblStruktur2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStruktur2MouseClicked
        // TODO add your handling code here:
        //        this.setVisible(false);
        //        new FormLaporan().setVisible(true);
    }//GEN-LAST:event_lblStruktur2MouseClicked

    private void lblProfilDesa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProfilDesa1MouseClicked
        // TODO add your handling code here:
        //        this.setVisible(false);
        //        new FormAnggota().setVisible(true);
    }//GEN-LAST:event_lblProfilDesa1MouseClicked

    private void lblStruktur3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStruktur3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblStruktur3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Psamping;
    private javax.swing.JPanel Psamping1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblEvaluasi;
    private javax.swing.JLabel lblEvaluasi1;
    private javax.swing.JLabel lblFuzzy;
    private javax.swing.JLabel lblFuzzy1;
    private javax.swing.JLabel lblHistory;
    private javax.swing.JLabel lblHistory1;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblHome1;
    private javax.swing.JLabel lblProfilDesa;
    private javax.swing.JLabel lblProfilDesa1;
    private javax.swing.JLabel lblStruktur;
    private javax.swing.JLabel lblStruktur1;
    private javax.swing.JLabel lblStruktur2;
    private javax.swing.JLabel lblStruktur3;
    // End of variables declaration//GEN-END:variables
}
