/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penerimaan.desa;

/**
 *
 * @author Imul
 */
public class HomePanel extends javax.swing.JPanel {
    
    private int role;
    DbConnection dc = new DbConnection("penerimaan_desa");

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
    }
    
    public HomePanel(int role) {
        initComponents();
        this.role = role;
        if (role > 0) {
//            navUser.setVisible(false);
//            navHistory.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        logout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxPekerjaan = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtPendapatan = new javax.swing.JTextField();
        txtJumlahTanggunganKeluarga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        lblLogo1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLuasLahan = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(210, 430, 280, 23);

        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        add(logout);
        logout.setBounds(724, 10, 60, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nomor Identitas");
        add(jLabel1);
        jLabel1.setBounds(130, 220, 180, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Luas Lahan");
        add(jLabel2);
        jLabel2.setBounds(130, 260, 90, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Jumlah Tanggungan Keluarga");
        add(jLabel3);
        jLabel3.setBounds(130, 300, 190, 20);
        add(txtNomor);
        txtNomor.setBounds(330, 220, 290, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Pekerjaan");
        add(jLabel4);
        jLabel4.setBounds(130, 340, 90, 20);

        cbxPekerjaan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buruh", "Petani", "Wiraswasta" }));
        add(cbxPekerjaan);
        cbxPekerjaan.setBounds(330, 340, 290, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Pendapatan");
        add(jLabel5);
        jLabel5.setBounds(130, 380, 190, 20);
        add(txtPendapatan);
        txtPendapatan.setBounds(330, 380, 290, 20);
        add(txtJumlahTanggunganKeluarga);
        txtJumlahTanggunganKeluarga.setBounds(330, 300, 290, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Nama Kepala Rumah Tangga");
        add(jLabel8);
        jLabel8.setBounds(130, 180, 180, 20);
        add(txtNama);
        txtNama.setBounds(330, 180, 290, 20);

        lblLogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penerimaan/desa/image/LogoDesa.jpg"))); // NOI18N
        add(lblLogo1);
        lblLogo1.setBounds(20, 10, 100, 126);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Kantor Kepala Desa Kasreman");
        add(jLabel6);
        jLabel6.setBounds(130, 10, 510, 100);
        add(txtLuasLahan);
        txtLuasLahan.setBounds(330, 260, 290, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
//        String nama = txtNama.getText();
//        String nomor = txtNomor.getText();
//        double luasLahan = Double.parseDouble(txtLuasLahan.getText());
//        double jumlahTanggunganKeluarga = Double.parseDouble(txtJumlahTanggunganKeluarga.getText());
//        String pekerjaan = cbxPekerjaan.getSelectedItem().toString();
//        double pendapatan = Double.parseDouble(txtPendapatan.getText());
//        Fuzzification f = new Fuzzification();
//        double hasil = f.calculation(luasLahan, jumlahTanggunganKeluarga, pekerjaan, pendapatan);
//        String layak = hasil > 50 ? "Layak":"Tidak Layak";
//        Statement st;
//        try {
//            st = dc.con.createStatement();
//            st.executeUpdate("INSERT INTO `history` (`id`, `nama` ,`nomor`, `luas_lahan`, `jumlah_tanggungan_keluarga`, `pekerjaan`, `pendapatan`, `kesimpulan`) VALUES (NULL, '"+nama+"', '"+nomor+"', '"+luasLahan+"', '"+jumlahTanggunganKeluarga+"', '"+pekerjaan+"', '"+pendapatan+"', '"+layak+"')");
//            new Hasil(this.role, nama, nomor, luasLahan, jumlahTanggunganKeluarga, pekerjaan, pendapatan, layak).setVisible(true);
//            this.dispose();
//        } catch (SQLException ex) {
//            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbxPekerjaan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel logout;
    private javax.swing.JTextField txtJumlahTanggunganKeluarga;
    private javax.swing.JTextField txtLuasLahan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNomor;
    private javax.swing.JTextField txtPendapatan;
    // End of variables declaration//GEN-END:variables
}
