/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penerimaan.desa;


/**
 *
 * @author Imul
 */
public class MainFrame extends javax.swing.JFrame {
    
    private int role;

    /**
     * Creates new form MainFrame
     */
    public MainFrame(int role) {
        initComponents();
        if (role > 0) {
            MnAdmin.setVisible(false);
            MnAturan.setVisible(false);
        }
        this.setVisible(true);
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pContent = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnFile = new javax.swing.JMenu();
        MnLogout = new javax.swing.JMenuItem();
        MnMaster = new javax.swing.JMenu();
        MnAdmin = new javax.swing.JMenuItem();
        MnWarga = new javax.swing.JMenuItem();
        MnTransaksi = new javax.swing.JMenu();
        MnAturan = new javax.swing.JMenuItem();
        MnNilai = new javax.swing.JMenuItem();
        MnHitung = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1370, 770));
        getContentPane().setLayout(new java.awt.CardLayout());

        pContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pContentLayout = new javax.swing.GroupLayout(pContent);
        pContent.setLayout(pContentLayout);
        pContentLayout.setHorizontalGroup(
            pContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        pContentLayout.setVerticalGroup(
            pContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(pContent, "card2");

        MnFile.setText("File");

        MnLogout.setText("Logout");
        MnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnLogoutActionPerformed(evt);
            }
        });
        MnFile.add(MnLogout);

        jMenuBar1.add(MnFile);

        MnMaster.setText("Master Data");
        MnMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnMasterActionPerformed(evt);
            }
        });

        MnAdmin.setText("Data Admin");
        MnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAdminActionPerformed(evt);
            }
        });
        MnMaster.add(MnAdmin);

        MnWarga.setText("Data Warga");
        MnWarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnWargaActionPerformed(evt);
            }
        });
        MnMaster.add(MnWarga);

        jMenuBar1.add(MnMaster);

        MnTransaksi.setText("Transaksi");

        MnAturan.setText("Aturan");
        MnAturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAturanActionPerformed(evt);
            }
        });
        MnTransaksi.add(MnAturan);

        MnNilai.setText("Nilai Mahasiswa");
        MnNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnNilaiActionPerformed(evt);
            }
        });
        MnTransaksi.add(MnNilai);

        MnHitung.setText("Perhitungan");
        MnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnHitungActionPerformed(evt);
            }
        });
        MnTransaksi.add(MnHitung);

        jMenuBar1.add(MnTransaksi);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnLogoutActionPerformed
        // TODO add your handling code here:
        new Login();
        this.dispose();
    }//GEN-LAST:event_MnLogoutActionPerformed

    private void MnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAdminActionPerformed
        // TODO add your handling code here:
        this.add(new UserPanel());
        this.remove(pContent);
        this.revalidate();
    }//GEN-LAST:event_MnAdminActionPerformed

    private void MnWargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnWargaActionPerformed
        // TODO add your handling code here:
        this.add(pContent);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_MnWargaActionPerformed

    private void MnAturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAturanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnAturanActionPerformed

    private void MnNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnNilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnNilaiActionPerformed

    private void MnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnHitungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnHitungActionPerformed

    private void MnMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnMasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnMasterActionPerformed

    public void setRole(int role){
        this.role = role;
    }
    
    public int getRole(){
        return this.role;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnAdmin;
    private javax.swing.JMenuItem MnAturan;
    private javax.swing.JMenu MnFile;
    private javax.swing.JMenuItem MnHitung;
    private javax.swing.JMenuItem MnLogout;
    private javax.swing.JMenu MnMaster;
    private javax.swing.JMenuItem MnNilai;
    private javax.swing.JMenu MnTransaksi;
    private javax.swing.JMenuItem MnWarga;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel pContent;
    // End of variables declaration//GEN-END:variables
}
