/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penerimaan.desa;


/**
 *
 * @author Imul
 */
public class MainFrame extends javax.swing.JFrame {
    
    private int role;
    private UserPanel userPanel = new UserPanel();
    private WargaPanel wargaPanel = new WargaPanel();
    private RulePanel rulePanel = new RulePanel();
    private KeputusanPanel keputusanPanel = new KeputusanPanel();
    private ProfilPanel profilPanel = new ProfilPanel();
    private PerhitunganPanel perhitunganPanel = new PerhitunganPanel();
    private PengujianPanel pengujianPanel = new PengujianPanel();

    /**
     * Creates new form MainFrame
     */
    public MainFrame(int role) {
        initComponents();
        if (role > 0) {
            MnAdmin.setVisible(false);
            MnAturan.setVisible(false);
        }
        this.setVisible(true);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.add(userPanel);
        this.add(wargaPanel);
        this.add(rulePanel);
        this.add(keputusanPanel);
        this.add(profilPanel);
        this.add(perhitunganPanel);
        this.add(pengujianPanel);
    }
    
    private void clearAllContent(){
        pContent.setVisible(false);
        userPanel.cleanAction();
        userPanel.setVisible(false);
        wargaPanel.cleanAction();
        wargaPanel.setVisible(false);
        rulePanel.setVisible(false);
        keputusanPanel.setVisible(false);
        profilPanel.setVisible(false);
        perhitunganPanel.setVisible(false);
        pengujianPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pContent = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnFile = new javax.swing.JMenu();
        MnLogout = new javax.swing.JMenuItem();
        MnMaster = new javax.swing.JMenu();
        MnAdmin = new javax.swing.JMenuItem();
        MnWarga = new javax.swing.JMenuItem();
        MnAturan = new javax.swing.JMenuItem();
        MnTransaksi = new javax.swing.JMenu();
        MnKeputusan = new javax.swing.JMenuItem();
        MnPerhitungan = new javax.swing.JMenuItem();
        MnPengujian = new javax.swing.JMenuItem();
        MnProfil = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1370, 770));
        getContentPane().setLayout(new java.awt.CardLayout());

        pContent.setBackground(new java.awt.Color(255, 255, 255));
        pContent.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Sistem Pendukung Keputusan");
        pContent.add(jLabel12);
        jLabel12.setBounds(507, 260, 356, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Penerimaan Bantuan Pangan Non Tunai Warga Desa Sukorejo");
        pContent.add(jLabel3);
        jLabel3.setBounds(210, 299, 950, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penerimaan/desa/image/bg-1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMinimumSize(new java.awt.Dimension(1370, 750));
        jLabel1.setPreferredSize(new java.awt.Dimension(1370, 750));
        pContent.add(jLabel1);
        jLabel1.setBounds(0, -220, 1370, 1010);

        jLabel2.setText("jLabel2");
        pContent.add(jLabel2);
        jLabel2.setBounds(510, 350, 34, 14);

        getContentPane().add(pContent, "card2");

        jMenuBar1.setPreferredSize(new java.awt.Dimension(246, 20));

        MnFile.setText("File");

        MnLogout.setText("Logout");
        MnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnLogoutActionPerformed(evt);
            }
        });
        MnFile.add(MnLogout);

        jMenuBar1.add(MnFile);

        MnMaster.setText("Master Data");
        MnMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnMasterActionPerformed(evt);
            }
        });

        MnAdmin.setText("Data Admin");
        MnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAdminActionPerformed(evt);
            }
        });
        MnMaster.add(MnAdmin);

        MnWarga.setText("Data Warga");
        MnWarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnWargaActionPerformed(evt);
            }
        });
        MnMaster.add(MnWarga);

        MnAturan.setText("Data Aturan");
        MnAturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAturanActionPerformed(evt);
            }
        });
        MnMaster.add(MnAturan);

        jMenuBar1.add(MnMaster);

        MnTransaksi.setText("Dana Bantuan");

        MnKeputusan.setText("Hasil Keputusan");
        MnKeputusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnKeputusanActionPerformed(evt);
            }
        });
        MnTransaksi.add(MnKeputusan);

        MnPerhitungan.setText("Hasil Perhitungan");
        MnPerhitungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnPerhitunganActionPerformed(evt);
            }
        });
        MnTransaksi.add(MnPerhitungan);

        MnPengujian.setText("Pengujian");
        MnPengujian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnPengujianActionPerformed(evt);
            }
        });
        MnTransaksi.add(MnPengujian);

        jMenuBar1.add(MnTransaksi);

        MnProfil.setText("Profil Desa");
        MnProfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnProfilMouseClicked(evt);
            }
        });
        MnProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnProfilActionPerformed(evt);
            }
        });
        jMenuBar1.add(MnProfil);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnLogoutActionPerformed
        // TODO add your handling code here:
        new Login();
        this.dispose();
    }//GEN-LAST:event_MnLogoutActionPerformed

    private void MnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAdminActionPerformed
        // TODO add your handling code here:
        this.clearAllContent();
        this.userPanel.setTable();
        this.userPanel.setVisible(true);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_MnAdminActionPerformed

    private void MnWargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnWargaActionPerformed
        // TODO add your handling code here:
        this.clearAllContent();
        this.wargaPanel.setTable();
        this.wargaPanel.setVisible(true);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_MnWargaActionPerformed

    private void MnAturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAturanActionPerformed
        // TODO add your handling code here:
        this.clearAllContent();
        this.rulePanel.setTable();
        this.rulePanel.setVisible(true);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_MnAturanActionPerformed

    private void MnKeputusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnKeputusanActionPerformed
        // TODO add your handling code here:
        this.clearAllContent();
        this.keputusanPanel.setTable();
        this.keputusanPanel.setVisible(true);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_MnKeputusanActionPerformed

    private void MnMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnMasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnMasterActionPerformed

    private void MnPerhitunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnPerhitunganActionPerformed
        // TODO add your handling code here:
        this.clearAllContent();
        this.perhitunganPanel.getData();
        this.perhitunganPanel.setVisible(true);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_MnPerhitunganActionPerformed

    private void MnPengujianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnPengujianActionPerformed
        // TODO add your handling code here:
        this.clearAllContent();
        this.pengujianPanel.setTable();
        this.pengujianPanel.setVisible(true);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_MnPengujianActionPerformed

    private void MnProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnProfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnProfilActionPerformed

    private void MnProfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnProfilMouseClicked
        // TODO add your handling code here:
        this.clearAllContent();
        this.profilPanel.setVisible(true);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_MnProfilMouseClicked

    public void setRole(int role){
        this.role = role;
    }
    
    public int getRole(){
        return this.role;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnAdmin;
    private javax.swing.JMenuItem MnAturan;
    private javax.swing.JMenu MnFile;
    private javax.swing.JMenuItem MnKeputusan;
    private javax.swing.JMenuItem MnLogout;
    private javax.swing.JMenu MnMaster;
    private javax.swing.JMenuItem MnPengujian;
    private javax.swing.JMenuItem MnPerhitungan;
    private javax.swing.JMenu MnProfil;
    private javax.swing.JMenu MnTransaksi;
    private javax.swing.JMenuItem MnWarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel pContent;
    // End of variables declaration//GEN-END:variables
}
