/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penerimaan.desa;

/**
 *
 * @author Imul
 */
public class ProfilPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfilPanel
     */
    public ProfilPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penerimaan/desa/image/LogoDesa.jpg"))); // NOI18N
        add(jLabel9);
        jLabel9.setBounds(300, 10, 160, 170);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Babat Bumi Sukorejo");
        add(jLabel10);
        jLabel10.setBounds(630, 130, 170, 50);
        jLabel10.getAccessibleContext().setAccessibleName("Babat Bumi Sukorejo, Gunung Pati");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Sejarah Desa Sukorejo, Gunung Pati");
        add(jLabel11);
        jLabel11.setBounds(500, 60, 440, 50);
        jLabel11.getAccessibleContext().setAccessibleName("Sejarah Desa Sukorejo Gunung Pati");

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane1.setText("             Konon menurut cerita, asal usul nama Desa Sukorejo berasal dari dua kata, yaitu Sukodan dan Rejo. Kata Sukodan memiliki makna senang, gembira atau bahagia sedangkan kata Rejo berarti Rejeh atau melimpah rejekinya. Berdasarkan dua makna tersebut, nama Sukorejo berusaha untuk menggambarkan bahwa masyarakat desa itu merupakan manusia yang senang, gembira dengan rejeki yang melimpah (rejeh), tetapi tidak melalaikan kewajiban kepada Allah SWT dalam melaksanakan perintah agama (ibadah) dan menjauhi larangan yang telah digariskan oleh agama.\n             \n             Desa Sukorejo sebagai satu-satunya desa yang terletak paling selatan merupakan desa yang kharismatik dan unik. Sejarah berdirinya Desa Sukorejo hingga kini masih misterius; tidak seorang pun mengetahuinya secara lengkap. Sejarah nama Desa Sukorejo hanya terdengar sepintas dari mulut ke mulut, yaitu kemungkinan ada sangkut pautnya dengan nama “Sukorejo” yang menggambarkan masyarakat makmur, gemah ripah loh jinawi toto tenterem kerto raharjo.              \n            \n             Masyarakat desa setempat atau tetangga desa bahkan lebih mengenal Desa Sukorejo dengan nama Arjosari. Nama Arjosari jauh lebih melekat dalam sanubari masyarakat setempat. Oleh karena itu gambaran yang ada di dalam masyarakat merupakan cerminan yang muncul bahwa masyarakat Sukorejo adalah masyarakat yang periang gembira, senang, ramah, rejo, dan rejeki dalam kehidupannya.");
        jScrollPane2.setViewportView(jTextPane1);

        add(jScrollPane2);
        jScrollPane2.setBounds(360, 190, 650, 350);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penerimaan/desa/image/bg-1.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -90, 1369, 950);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
