/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penerimaan.desa;

import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Imul
 */
public class UserCreate extends javax.swing.JFrame {
    
    DbConnection dc = new DbConnection("penerimaan_desa");
    private int role;

    /**
     * Creates new form CreateUser
     */
    public UserCreate() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTambKaryawan2 = new javax.swing.JLabel();
        lblUsername2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btntambah = new javax.swing.JToggleButton();
        btnreset = new javax.swing.JToggleButton();
        lblPassword5 = new javax.swing.JLabel();
        cbxRole = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        lblTambKaryawan2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTambKaryawan2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTambKaryawan2.setText("Tambah User");
        jPanel1.add(lblTambKaryawan2);
        lblTambKaryawan2.setBounds(10, 10, 310, 44);

        lblUsername2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsername2.setText("Username");
        jPanel1.add(lblUsername2);
        lblUsername2.setBounds(140, 180, 100, 22);

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtUsername);
        txtUsername.setBounds(390, 180, 250, 28);

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassword.setText("Password");
        jPanel1.add(lblPassword);
        lblPassword.setBounds(140, 210, 90, 22);

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtPassword);
        txtPassword.setBounds(390, 210, 250, 28);

        btntambah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btntambah.setText("Tambah");
        btntambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntambahMouseClicked(evt);
            }
        });
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel1.add(btntambah);
        btntambah.setBounds(390, 290, 115, 31);

        btnreset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnresetMouseClicked(evt);
            }
        });
        jPanel1.add(btnreset);
        btnreset.setBounds(520, 290, 115, 31);

        lblPassword5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassword5.setText("Role");
        jPanel1.add(lblPassword5);
        lblPassword5.setBounds(140, 240, 90, 22);

        cbxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff" }));
        jPanel1.add(cbxRole);
        cbxRole.setBounds(390, 240, 250, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntambahMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btntambahMouseClicked

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
                                             
        if(txtUsername.getText().equals("") || txtPassword.getText().equals("")) JOptionPane.showMessageDialog(this, "Username dan Passsword Wajib diisi.");
        else{
            try{
                Statement st = dc.con.createStatement();
                st.executeUpdate("INSERT INTO `users` (`user_id`, `username`, `password`, `role`) VALUES (NULL, '"+txtUsername.getText()+"', '"+txtPassword.getText()+"', '"+cbxRole.getSelectedIndex()+"')");
                this.dispose();
            }catch(SQLException e){
                System.out.println("Error : "+e);
            }
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnresetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnresetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnresetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserCreate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnreset;
    private javax.swing.JToggleButton btntambah;
    private javax.swing.JComboBox<String> cbxRole;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword5;
    private javax.swing.JLabel lblTambKaryawan2;
    private javax.swing.JLabel lblUsername2;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
